#include"Pointers.h"
#include"C_StyleArrays.h"
#include "C_StyleStrings.h"
#include "Macros.h"
#include"FunctionPointers.h"
#include "Containers.h"
#include"Lambda.h"
#include "Algorithm.h"
#include "moveSematics.h"
#include "Exception.h"
#include"array.h"
#include"vector.h"
#include"list.h"
#include"Pair.h"
#include"map.h"
#include"set.h"
#include"queue.h"
#include"deque.h"
#include"stack.h"
#include"tuple.h"
#include"Algorithm.h"
#include "Obsever.h"
#include"StatePattern.h"
#include"StrategyPattern.h"
#include "TemplateMethode.h"
#include"Visitorpattern.h"
#include"ChainOfResponsablity.h"
#include"CommandPattern.h"
#include"InterpreterPattern.h"
#include"IteratorPattern.h"
#include "MementoPattern.h"
#include "NullObj.h"
#include "Solid.h"
#include"Singleton.h"
#include "Builder.h"
#include"Prototype.h"
#include"Factory_method.h"
#include"Abstract_factory.h"
#include"InitMultiThreading.h"
#include"Adapter.h"
#include"Bridge.h"
#include"Composite.h"
#include "DecoratorPattern.h"
#include<Windows.h>

int main()
{
	Algorithm a;
	a.execute();
}